export const BACKGROUND_COLORS = {
    'Zoom': '--color-background-zoom',
    'Aqua': '--color-background-aqua',
    'Black': '--color-background-black',
    'Blue': '--color-background-blue',
    'Brand': '--color-background-brand',
    'Cool Gray': '--color-background-cool-gray',
    'Gray': '--color-background-gray',
    'Green': '--color-background-green',
    'Orange Red': '--color-background-orange-red',
    'Orange': '--color-background-orange',
    'Purple': '--color-background-purple',
    'Red': '--color-background-red',
    'Transparent': '--color-background-transparent',
    'White': '--color-background-white',
    'Yellow': '--color-background-yellow',
    'Bold Aqua': '--color-background-bold-aqua',
    'Bold Blue': '--color-background-bold-blue',
    'Bold Cool Gray': '--color-background-bold-cool-gray',
    'Bold Gray': '--color-background-bold-gray',
    'Bold Green': '--color-background-bold-green',
    'Bold Orange Red': '--color-background-bold-orange-red',
    'Bold Orange': '--color-background-bold-orange',
    'Bold Purple': '--color-background-bold-purple',
    'Bold Red': '--color-background-bold-red',
    'Bold Yellow': '--color-background-bold-yellow',
};